# -*- coding: utf-8 -*-
"""Assignment1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PgS7IdojuZ1_fuke0vLvGGXchoGav3Hs
"""



import pandas as pd

# Creating DeptTable
DeptTable = pd.DataFrame({
    'Dept_ID':[1003,1001,1002],
    'Dept_Name':['A','B','C'],
    'Dept_StartYear':[2010,2000,2005]
    })

# Creating EmployeeTable
EmployeeTable = pd.DataFrame({
    'Emp_ID':['Emp1','Emp2','Emp3','Emp4','Emp5','Emp6'],
    'Dept_ID':[1001,1002,1002,1002,1001,1002]
    })

print("Write a python code to define the DeptTable and EmployeeTable tables.\n")
print("DeptTable:")
print(DeptTable)
print("\nEmployeeTable:")
print(EmployeeTable)
print("\n")

# Find the newest department
print("Write a python code that returns the name of the newest department.")
newest_dept = DeptTable.loc[DeptTable['Dept_StartYear'].idxmax(), 'Dept_Name']
print("The newest department is:", newest_dept)
print("\n")

print("Smallest number of employees along with its number of employees.")
merged_table = pd.merge(DeptTable, EmployeeTable, on='Dept_ID', how='left')
print(merged_table)
# Count the number of employees in each department
employee_count = merged_table.groupby('Dept_ID')['Emp_ID'].count()
print(employee_count)
# Get the department with the smallest number of employees (including zero)
min_dept_row = DeptTable.set_index('Dept_ID').loc[employee_count.idxmin()]
min_dept_name = min_dept_row['Dept_Name']
min_emp_count = employee_count.min()
print(f"The department with the smallest number of employees is {min_dept_name} with {min_emp_count} employees.")
print("\n")